version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: focuscards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=focuscards
      - POSTGRES_PORT=5432
      - BACKEND_CORS_ORIGINS=["http://localhost:5174","http://127.0.0.1:5174"]
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload

  frontend:
    build: ./frontend
    ports:
      - "5174:5174"
    environment:
      - PORT=5174
      - REACT_APP_API_URL=http://localhost:8080/api/v1
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

volumes:
  postgres_data: